const sourceEl = document.querySelector("#source");
const outputEl = document.querySelector("#output");
const statusEl = document.querySelector("#status");
const summaryEl = document.querySelector("#summary");
const generatorStatusEl = document.querySelector("#generator-status");
let source = null;
let outputType = "clash";
const routeDescriptions = { Apple: "Apple 服务直连", AI: "ChatGPT、Gemini、Claude、Perplexity 等 AI 服务", LINE: "LINE 服务", Netflix: "Netflix 与 Fast.com", YouTube: "YouTube 视频服务", TikTok: "TikTok 短视频服务", Google: "Google 服务", "局域网直连": "局域网、保留地址与特殊网段" };
const speedTests = { Cloudflare: "http://cp.cloudflare.com/generate_204", Fast: "https://fast.com", Gstatic: "http://www.gstatic.com/generate_204" };
const ruleGroupPatterns = {
  Apple: [{ name: "Apple Relay", domains: ["apple-relay.akamaized.net", "apple-relay.apple.com", "apple-relay.cloudflare.com", "apple-relay.fastly-edge.com", "apple-relay.mask.apple-dns.net"] }, { name: "Apple 服务", domains: ["apple.com", "icloud.com"] }],
  AI: [{ name: "ChatGPT", domains: ["openai.com", "chatgpt.com", "oaistatic.com", "oaiusercontent.com"] }, { name: "Gemini", domains: ["gemini.google.com"] }, { name: "Claude", domains: ["claude.ai", "anthropic.com", "claudeusercontent.com"] }, { name: "Perplexity", domains: ["perplexity.ai"] }],
  LINE: [{ name: "LINE CDN", domains: ["line-cdn.net", "line-scdn.net"] }, { name: "LINE 服务", domains: ["line.naver.jp", "line.me", "line-apps.com"] }],
  Netflix: [{ name: "Netflix 主站", domains: ["netflix.com", "netflix.net"] }, { name: "Netflix CDN", domains: ["nflximg.net", "nflxvideo.net", "nflxso.net", "nflxext.com"] }, { name: "Fast.com", domains: ["fast.com"] }],
  YouTube: [{ name: "YouTube 短链接", domains: ["youtu.be"] }, { name: "YouTube CDN", domains: ["ytimg.com", "googlevideo.com"] }, { name: "YouTube 主站", domains: ["youtube.com"] }],
  TikTok: [{ name: "TikTok 主站", domains: ["tiktok.com", "tiktokv.com"] }, { name: "TikTok CDN", domains: ["tiktokcdn.com"] }, { name: "Musical.ly", domains: ["musical.ly", "muscdn.com"] }],
  Google: [{ name: "Google API", domains: ["googleapis.com"] }, { name: "Google 静态资源", domains: ["gstatic.com", "ggpht.com"] }, { name: "Google 主站", domains: ["google.com"] }, { name: "Google 视频", domains: ["googlevideo.com"] }, { name: "Google 用户内容", domains: ["googleusercontent.com"] }],
};

const marker = (type) => type === "clash"
  ? "// Generated by the Clash JS / Shadowrocket rule generator; edit rules-source.json instead."
  : "# Generated by the Clash JS / Shadowrocket rule generator; edit rules-source.json instead.";

function routeDomains(data, route) { return [...(route.domain_sets || []).flatMap((name) => data.rule_sets[name] || []), ...(route.domains || [])]; }

function routeRuleEntries(data, route) {
  const domainTargets = route.domain_targets || route._domainTargets || [];
  return [
    ...routeDomains(data, route).map((value, index) => ({ kind: "域名", value, target: domainTargets[index] || route.target })),
    ...(route.cidrs || []).map((value) => ({ kind: "IP/CIDR", value, target: route.target })),
    ...(route.geoips || []).map((value) => ({ kind: "GeoIP", value, target: route.target })),
  ];
}

function ruleGroupName(route, entry) {
  if (entry.kind !== "域名") return entry.kind;
  const value = entry.value.toLowerCase();
  const group = (ruleGroupPatterns[route.name] || []).find(({ domains }) => domains.some((domain) => value === domain || value.endsWith(`.${domain}`)));
  return group?.name || "其他规则";
}

function expandedRoutes(data) {
  return [...data.routes.flatMap((route) => {
    const domains = routeDomains(data, route);
    const domainTargets = route.domain_targets || route._domainTargets;
    if (!domainTargets?.length) return [{ ...route, domain_sets: [], domains }];
    const domainRoutes = domains.map((domain, index) => ({ name: route.name, target: domainTargets[index] || route.target, domains: [domain] }));
    const otherRules = { name: route.name, target: route.target, geoips: route.geoips || [], keywords: route.keywords || [], cidrs: route.cidrs || [] };
    return [...domainRoutes, ...(otherRules.geoips.length || otherRules.keywords.length || otherRules.cidrs.length ? [otherRules] : [])];
  }), ...(data.standalone_urls || []).map((item) => ({ name: item.name, target: item.target, domains: [item.domain] })), ...(data.standalone_rules || [])];
}

function rules(data, finalType) {
  return [...expandedRoutes(data).flatMap((route) => {
    const target = data.targets[route.target];
    return [
      ...(route.geoips || []).map((value) => [`GEOIP,${value},${target}`, route.name]),
      ...(route.domains || []).map((value) => [`DOMAIN-SUFFIX,${value},${target}`, route.name]),
      ...(route.keywords || []).map((value) => [`DOMAIN-KEYWORD,${value},${target}`, route.name]),
      ...(route.cidrs || []).map((value) => [`IP-CIDR,${value},${target},no-resolve`, route.name]),
    ];
  }), [`${finalType},${data.targets[data.final]}`, null]];
}

function renderClash(data) {
  const groups = data.groups.map((group) => ({
    target: group.target, pattern: group.pattern, flags: group.flags || "",
    url: group.url, interval: group.interval, tolerance: group.tolerance, fallback: group.fallback,
  }));
  return `${marker("clash")}\n\nconst TARGETS = Object.freeze(${JSON.stringify(data.targets, null, 2)});\nconst GROUP_CONFIGS = ${JSON.stringify(groups, null, 2)};\nconst ROUTES = ${JSON.stringify(expandedRoutes(data), null, 2)};\nconst FINAL_TARGET = ${JSON.stringify(data.final)};\nconst DNS_CONFIG = ${JSON.stringify(data.mihomo_dns, null, 2)};\n\nfunction compileRoute(route) {\n  const target = TARGETS[route.target];\n  return [\n    ...(route.geoips || []).map((value) => \`GEOIP,\${value},\${target}\`),\n    ...(route.domains || []).map((value) => \`DOMAIN-SUFFIX,\${value},\${target}\`),\n    ...(route.keywords || []).map((value) => \`DOMAIN-KEYWORD,\${value},\${target}\`),\n    ...(route.cidrs || []).map((value) => \`IP-CIDR,\${value},\${target},no-resolve\`),\n  ];\n}\n\nfunction buildProxyGroups(proxies) {\n  return GROUP_CONFIGS.map((group) => {\n    const match = new RegExp(group.pattern, group.flags);\n    const matchedProxies = proxies.filter((proxy) => match.test(proxy.name)).map((proxy) => proxy.name);\n    return { name: TARGETS[group.target], type: "url-test", url: group.url, interval: group.interval, tolerance: group.tolerance, proxies: matchedProxies.length ? matchedProxies : [TARGETS[group.fallback]] };\n  });\n}\n\nfunction main(config) {\n  config["proxy-groups"] ||= [];\n  config["proxy-groups"].unshift(...buildProxyGroups(config.proxies || []));\n  config.dns = DNS_CONFIG;\n  config.rules = [...ROUTES.flatMap(compileRoute), \`MATCH,\${TARGETS[FINAL_TARGET]}\`, ...(config.rules || [])];\n  return config;\n}\n`;
}

function renderShadowrocket(data) {
  const dns = data.shadowrocket_dns;
  const lines = [marker("shadowrocket"), "# Clash 在零匹配时回退到 fallback；Shadowrocket 使用静态策略组。", "", "[General]",
    `ipv6 = ${dns.ipv6}`, `prefer-ipv6 = ${dns.prefer_ipv6}`, `private-ip-answer = ${dns.private_ip_answer}`,
    `dns-direct-system = ${dns.dns_direct_system}`, `dns-direct-fallback-proxy = ${dns.dns_direct_fallback_proxy}`,
    `hijack-dns = ${dns.hijack_dns.join(",")}`, `dns-server = ${dns.servers.join(",")}`,
    `fallback-dns-server = ${dns.fallback_servers.join(",")}`, `proxy-dns-server = ${dns.proxy_servers.join(",")}`,
    `always-real-ip = ${dns.always_real_ip.join(",")}`, "", "[Proxy Group]"];
  for (const group of data.groups) lines.push(`${data.targets[group.target]} = url-test,url=${group.url},interval=${group.interval},tolerance=${group.tolerance},policy-regex-filter=${group.flags === "i" ? "(?i)" : ""}${group.pattern}`);
  lines.push("", "[Rule]");
  let previous = null;
  for (const [rule, name] of rules(data, "FINAL")) { if (name && name !== previous) { lines.push("", `# ${name}`); previous = name; } lines.push(rule); }
  lines.push("", "[Host]");
  for (const mapping of dns.host_servers) for (const pattern of mapping.patterns) lines.push(`${pattern} = server:${mapping.server}`);
  return `${lines.join("\n")}\n`;
}

const domainPattern = /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i;

function validCidr(value) {
  const [address, prefix, ...rest] = String(value).split("/");
  if (!address || rest.length || !/^\d+$/.test(prefix)) return false;
  const bits = address.includes(":") ? 128 : 32;
  if (Number(prefix) > bits) return false;
  if (bits === 128) { try { return new URL(`http://[${address}]`).hostname !== ""; } catch { return false; } }
  const octets = address.split(".");
  return octets.length === 4 && octets.every((octet) => /^(0|[1-9]\d{0,2})$/.test(octet) && Number(octet) <= 255);
}

function validate(data) {
  if (!data || data.version !== 1 || !data.targets || !data.rule_sets || !Array.isArray(data.groups) || !Array.isArray(data.routes) || !data.final) throw new Error("必须包含 version、targets、rule_sets、groups、routes 和 final 字段");
  for (const [name, values] of Object.entries(data.rule_sets)) if (!Array.isArray(values) || values.some((value) => typeof value !== "string" || !value)) throw new Error(`规则集「${name}」配置无效`);
  for (const group of data.groups) {
    if (!data.targets[group.target] || !data.targets[group.fallback]) throw new Error(`节点组「${group.target || "未命名"}」引用了未知策略`);
    if (typeof group.pattern !== "string" || !group.pattern) throw new Error(`节点组「${group.target}」缺少节点名称正则`);
    if (!['', 'i'].includes(group.flags || "")) throw new Error(`节点组「${group.target}」正则标志无效`);
    try { new RegExp(group.pattern, group.flags || ""); } catch (error) { throw new Error(`节点组「${group.target}」正则错误：${error.message}`); }
    if (typeof group.url !== "string" || !/^https?:\/\//.test(group.url)) throw new Error(`节点组「${group.target}」测速地址无效`);
    if (!Number.isInteger(group.interval) || group.interval < 0 || !Number.isInteger(group.tolerance) || group.tolerance < 0) throw new Error(`节点组「${group.target}」测速参数无效`);
  }
  for (const route of data.routes) {
    if (!data.targets[route.target]) throw new Error(`规则「${route.name || "未命名"}」引用了未知策略`);
    for (const setName of route.domain_sets || []) if (!Array.isArray(data.rule_sets[setName])) throw new Error(`规则「${route.name || "未命名"}」引用了未知规则集`);
    for (const field of ["domains", "keywords", "cidrs", "geoips"]) if (route[field] && (!Array.isArray(route[field]) || route[field].some((value) => typeof value !== "string" || !value))) throw new Error(`规则「${route.name || "未命名"}」的 ${field} 配置无效`);
    for (const cidr of route.cidrs || []) if (!validCidr(cidr)) throw new Error(`CIDR 无效：${cidr}`);
    const domainTargets = route.domain_targets || route._domainTargets;
    if (domainTargets) {
      if (!Array.isArray(domainTargets) || domainTargets.length !== routeDomains(data, route).length) throw new Error(`规则「${route.name || "未命名"}」的网址目标数量不匹配`);
      if (domainTargets.some((target) => !data.targets[target])) throw new Error(`规则「${route.name || "未命名"}」引用了未知网址目标`);
    }
  }
  for (const item of data.standalone_urls || []) {
    if (!item.name || !item.domain || !domainPattern.test(item.domain)) throw new Error(`独立网址无效：${item.domain || "空值"}`);
    if (!data.targets[item.target]) throw new Error(`独立网址「${item.name}」引用了未知策略`);
  }
  for (const item of data.standalone_rules || []) {
    if (!item.name || !data.targets[item.target] || !["geoips", "domains", "cidrs"].some((field) => item[field]?.length)) throw new Error(`独立规则「${item.name || "未命名"}」配置无效`);
    for (const domain of item.domains || []) if (!domainPattern.test(domain)) throw new Error(`域名无效：${domain}`);
    for (const cidr of item.cidrs || []) if (!validCidr(cidr)) throw new Error(`CIDR 无效：${cidr}`);
    for (const geoip of item.geoips || []) if (!/^[A-Z]{2}$/i.test(geoip)) throw new Error(`GeoIP 无效：${geoip}`);
  }
  if (!data.targets[data.final]) throw new Error("final 引用了未知策略");
  const mihomoDns = data.mihomo_dns;
  if (!mihomoDns || typeof mihomoDns !== "object") throw new Error("缺少 mihomo_dns 配置");
  if (mihomoDns.enable !== true || !["arc", "lru"].includes(mihomoDns["cache-algorithm"]) || !["fake-ip", "redir-host"].includes(mihomoDns["enhanced-mode"])) throw new Error("mihomo_dns 基础配置无效");
  for (const field of ["default-nameserver", "fake-ip-filter", "nameserver", "fallback", "proxy-server-nameserver", "direct-nameserver"]) if (!Array.isArray(mihomoDns[field]) || mihomoDns[field].some((value) => typeof value !== "string" || !value || /[,\r\n]/.test(value))) throw new Error(`mihomo_dns.${field} 配置无效`);
  const fallbackFilter = mihomoDns["fallback-filter"];
  if (!fallbackFilter || fallbackFilter.geoip !== true || !/^[A-Z]{2}$/i.test(fallbackFilter["geoip-code"] || "") || !Array.isArray(fallbackFilter.geosite) || !Array.isArray(fallbackFilter.ipcidr) || !Array.isArray(fallbackFilter.domain)) throw new Error("mihomo_dns.fallback-filter 配置无效");
  const dns = data.shadowrocket_dns;
  if (!dns || typeof dns !== "object") throw new Error("缺少 shadowrocket_dns 配置");
  for (const field of ["ipv6", "prefer_ipv6", "private_ip_answer", "dns_direct_system", "dns_direct_fallback_proxy"]) if (typeof dns[field] !== "boolean") throw new Error(`shadowrocket_dns.${field} 必须是布尔值`);
  for (const field of ["servers", "fallback_servers", "proxy_servers", "always_real_ip", "hijack_dns"]) if (!Array.isArray(dns[field]) || !dns[field].length || dns[field].some((value) => typeof value !== "string" || !value || /[,\r\n]/.test(value))) throw new Error(`shadowrocket_dns.${field} 配置无效`);
  if (!Array.isArray(dns.host_servers) || !dns.host_servers.length) throw new Error("shadowrocket_dns.host_servers 配置无效");
}

function render() {
  try {
    source = JSON.parse(sourceEl.value); validate(source);
    outputEl.value = outputType === "clash" ? renderClash(source) : renderShadowrocket(source);
    const count = rules(source, "MATCH").length;
    summaryEl.textContent = `${count} 条规则 · ${source.routes.length} 个策略组 · ${(source.standalone_urls || []).length} 个独立网址 · ${(source.standalone_rules || []).length} 个独立规则 · 浏览器本地生成`;
    statusEl.textContent = "校验通过"; statusEl.className = ""; generatorStatusEl.textContent = "规则源校验通过"; generatorStatusEl.className = "generator-status";
  } catch (error) { statusEl.textContent = error.message; statusEl.className = "error"; generatorStatusEl.textContent = error.message; generatorStatusEl.className = "generator-status error"; summaryEl.textContent = "规则源无效"; outputEl.value = ""; }
}

async function loadDefault() {
  try { sourceEl.value = JSON.stringify(await (await fetch("rules-source.json")).json(), null, 2); render(); }
  catch { const message = "无法加载 rules-source.json，请使用下方「导入 JSON」选择本地规则源。"; statusEl.textContent = message; statusEl.className = "error"; generatorStatusEl.textContent = message; generatorStatusEl.className = "generator-status error"; document.querySelector("#converter-toolbar").classList.remove("hidden"); }
}

function setupGenerator(data) {
  if (!data.standalone_urls) {
    data.standalone_urls = [];
    for (const route of data.routes.filter((item) => ["Direct", "Daily / SEA"].includes(item.name))) {
      data.standalone_urls.push(...(route.domains || []).map((domain) => ({ name: domain, domain, target: route.target })));
      route.domains = [];
    }
  }
  let editingRoute = null;
  const renderRoutes = () => {
    const renderRoute = (route, index) => {
      const count = routeDomains(data, route).length + (route.keywords || []).length + (route.cidrs || []).length + (route.geoips || []).length;
      return `<div class="route-option"><div><input type="checkbox" aria-label="启用 ${escapeHtml(route.name)}" data-route="${index}" ${route.enabled !== false ? "checked" : ""}><strong>${escapeHtml(route.name)}</strong></div><em>${routeDescriptions[route.name] || "自定义分流规则"} · ${count} 条匹配规则</em><select data-target-route="${index}" aria-label="${escapeHtml(route.name)} 导向节点组">${Object.entries(data.targets).map(([key, name]) => `<option value="${escapeHtml(key)}" ${route.target === key ? "selected" : ""}>${escapeHtml(name)}</option>`).join("")}</select><button type="button" class="edit-domains" data-edit-route="${index}">编辑规则列表</button></div>`;
    };
    const routes = data.routes.map((route, index) => ({ route, index }));
    const baseRoutes = routes.filter(({ route }) => route.name === "局域网直连");
    document.querySelector("#route-options").innerHTML = routes.filter(({ route }) => route.name !== "局域网直连").map(({ route, index }) => renderRoute(route, index)).join("");
    document.querySelector("#base-rule-options").innerHTML = baseRoutes.map(({ route, index }) => renderRoute(route, index)).join("");
    document.querySelector("#base-rule-section").classList.toggle("hidden", !baseRoutes.length);
    document.querySelectorAll("[data-route]").forEach((input) => input.onchange = () => { data.routes[input.dataset.route].enabled = input.checked; });
    document.querySelectorAll("[data-target-route]").forEach((select) => select.onchange = () => { data.routes[select.dataset.targetRoute].target = select.value; });
    document.querySelectorAll("[data-edit-route]").forEach((button) => button.onclick = () => { editingRoute = Number(button.dataset.editRoute); const route = data.routes[editingRoute]; const entries = routeRuleEntries(data, route); let previousGroup = null; const renderEntry = (entry, index) => { const group = ruleGroupName(route, entry); const heading = group === previousGroup ? "" : `<h3 class="drawer-group">${escapeHtml(group)}</h3>`; previousGroup = group; return `${heading}<div class="drawer-item"><span>${entry.kind}</span><input aria-label="${escapeHtml(route.name)} ${entry.kind} ${index + 1}" data-drawer-value="${index}" data-drawer-kind="${entry.kind}" value="${escapeHtml(entry.value)}"><select aria-label="${escapeHtml(entry.value)} 导向节点组" data-drawer-target="${index}" ${entry.kind !== "域名" ? "disabled" : ""}>${Object.entries(data.targets).map(([key, name]) => `<option value="${escapeHtml(key)}" ${entry.target === key ? "selected" : ""}>${escapeHtml(name)}</option>`).join("")}</select></div>`; }; document.querySelector("#drawer-title").textContent = `${route.name} · 规则列表`; document.querySelector("#drawer-items").innerHTML = entries.map(renderEntry).join(""); document.querySelector("#drawer-backdrop").classList.remove("hidden"); document.querySelector("#domain-drawer").classList.remove("hidden"); document.querySelector("#domain-drawer").classList.add("open"); document.querySelector("#domain-drawer").setAttribute("aria-hidden", "false"); });
  };
  renderRoutes();
  const renderStandalone = () => { document.querySelector("#standalone-options").innerHTML = (data.standalone_urls || []).map((item, index) => `<div class="standalone-row"><input aria-label="网址名称" data-standalone-name="${index}" value="${escapeHtml(item.name)}"><input aria-label="网址" data-standalone-domain="${index}" value="${escapeHtml(item.domain)}"><select aria-label="目标节点组" data-standalone-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${key}" ${item.target === key ? "selected" : ""}>${name}</option>`).join("")}</select><button type="button" data-remove-standalone="${index}">删除</button></div>`).join(""); document.querySelectorAll("[data-standalone-name]").forEach((input) => input.oninput = () => { data.standalone_urls[input.dataset.standaloneName].name = input.value; }); document.querySelectorAll("[data-standalone-domain]").forEach((input) => input.oninput = () => { data.standalone_urls[input.dataset.standaloneDomain].domain = input.value.trim(); }); document.querySelectorAll("[data-standalone-target]").forEach((select) => select.onchange = () => { data.standalone_urls[select.dataset.standaloneTarget].target = select.value; }); document.querySelectorAll("[data-remove-standalone]").forEach((button) => button.onclick = () => { data.standalone_urls.splice(Number(button.dataset.removeStandalone), 1); renderStandalone(); }); };
  renderStandalone();
  document.querySelector("#add-standalone").onclick = () => { data.standalone_urls ||= []; data.standalone_urls.push({ name: "新网址", domain: "example.com", target: "DIRECT" }); renderStandalone(); };
  const renderRules = () => { document.querySelector("#rule-options").innerHTML = (data.standalone_rules || []).map((item, index) => ({ item, index })).filter(({ item }) => !item.geoips?.length).map(({ item, index }) => { const type = item.cidrs?.length ? "cidrs" : "domains"; return `<div class="standalone-rule"><input aria-label="规则名称" data-rule-name="${index}" value="${escapeHtml(item.name)}"><select aria-label="规则类型" data-rule-type="${index}"><option value="cidrs" ${type === "cidrs" ? "selected" : ""}>CIDR / IP</option><option value="domains" ${type === "domains" ? "selected" : ""}>域名</option></select><textarea aria-label="规则值" data-rule-values="${index}" spellcheck="false">${escapeHtml((item[type] || []).join("\n"))}</textarea><select aria-label="目标节点组" data-rule-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${escapeHtml(key)}" ${item.target === key ? "selected" : ""}>${escapeHtml(name)}</option>`).join("")}</select><button type="button" data-remove-rule="${index}">删除</button></div>`; }).join(""); };
  const renderGeoipRules = () => { document.querySelector("#geoip-options").innerHTML = (data.standalone_rules || []).map((item, index) => ({ item, index })).filter(({ item }) => item.geoips?.length).map(({ item, index }) => `<div class="standalone-rule geoip-rule"><input aria-label="GeoIP 规则名称" data-rule-name="${index}" value="${escapeHtml(item.name)}"><textarea aria-label="GeoIP 规则值" data-rule-values="${index}" data-rule-type="geoips" spellcheck="false">${escapeHtml(item.geoips.join("\n"))}</textarea><select aria-label="GeoIP 目标节点组" data-rule-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${escapeHtml(key)}" ${item.target === key ? "selected" : ""}>${escapeHtml(name)}</option>`).join("")}</select><button type="button" data-remove-rule="${index}">删除</button></div>`).join(""); };
  const syncRule = (index) => { const area = document.querySelector(`[data-rule-values="${index}"]`); const type = document.querySelector(`[data-rule-type="${index}"]`)?.value || "geoips"; data.standalone_rules[index][type] = area.value.split(/\r?\n/).map((value) => value.trim()).filter(Boolean); };
  const renderRuleLists = () => { renderRules(); renderGeoipRules(); document.querySelectorAll("[data-rule-name]").forEach((input) => input.oninput = () => { data.standalone_rules[input.dataset.ruleName].name = input.value; }); document.querySelectorAll("[data-rule-target]").forEach((select) => select.onchange = () => { data.standalone_rules[select.dataset.ruleTarget].target = select.value; }); document.querySelectorAll("[data-remove-rule]").forEach((button) => button.onclick = () => { data.standalone_rules.splice(Number(button.dataset.removeRule), 1); renderRuleLists(); }); };
  data.standalone_rules ||= []; renderRuleLists();
  document.querySelectorAll("#rule-options, #geoip-options").forEach((container) => { container.oninput = (event) => { if (event.target.matches("[data-rule-values]")) syncRule(Number(event.target.dataset.ruleValues)); }; container.onchange = (event) => { if (event.target.matches("[data-rule-type]")) renderRuleLists(); }; });
  document.querySelector("#add-rule").onclick = () => { data.standalone_rules.push({ name: "新规则", target: "DIRECT", cidrs: ["192.0.2.0/24"] }); renderRuleLists(); };
  document.querySelector("#add-geoip").onclick = () => { data.standalone_rules.push({ name: "新 GeoIP 规则", target: "DIRECT", geoips: ["CN"] }); renderRuleLists(); };
  document.querySelector("#add-route").onclick = () => { data.routes.push({ name: `新策略 ${data.routes.length + 1}`, target: "DIRECT", domains: [], keywords: [] }); renderRoutes(); };
  document.querySelector("#save-domains").onclick = () => { if (editingRoute === null) return; const route = data.routes[editingRoute]; const values = [...document.querySelectorAll("[data-drawer-value]")]; const targets = [...document.querySelectorAll("[data-drawer-target]")]; const entries = values.map((input, index) => ({ kind: input.dataset.drawerKind, value: input.value.trim(), target: targets[index]?.value || route.target })).filter((entry) => entry.value); const domains = entries.filter((entry) => entry.kind === "域名"); route.domain_sets = []; route.domains = domains.map((entry) => entry.value); route.domain_targets = domains.map((entry) => entry.target); route.cidrs = entries.filter((entry) => entry.kind === "IP/CIDR").map((entry) => entry.value); route.geoips = entries.filter((entry) => entry.kind === "GeoIP").map((entry) => entry.value); delete route._domainTargets; document.querySelector("#drawer-backdrop").click(); renderRoutes(); };
  document.querySelector("#close-drawer").onclick = () => document.querySelector("#drawer-backdrop").click();
  document.querySelector("#drawer-backdrop").onclick = () => { document.querySelector("#drawer-backdrop").classList.add("hidden"); document.querySelector("#domain-drawer").classList.add("hidden"); document.querySelector("#domain-drawer").classList.remove("open"); document.querySelector("#domain-drawer").setAttribute("aria-hidden", "true"); };
  document.querySelector("#group-interval").value = data.groups[0]?.interval ?? 30;
  document.querySelector("#group-tolerance").value = data.groups[0]?.tolerance ?? 10;
  const groupOptions = document.querySelector("#group-options");
  const renderGroups = () => {
    groupOptions.innerHTML = data.groups.map((group, index) => `<div class="group-row" data-group="${index}">
      <label><span>策略键</span><input readonly value="${escapeHtml(group.target)}"><small>稳定的规则引用名称</small></label>
      <label><span>显示名称</span><input data-display="${index}" value="${escapeHtml(data.targets[group.target] || group.target)}"><small>客户端显示的节点组名称</small></label>
      <label><span>节点名称正则</span><input data-field="pattern" value="${escapeHtml(group.pattern)}" placeholder="例如 新加坡|SG"><small>匹配节点名称后加入此组</small></label>
      <label><span>测速服务</span><select data-field="url">${Object.entries(speedTests).map(([name, url]) => `<option value="${url}" ${group.url === url ? "selected" : ""}>${name}</option>`).join("")}</select><small>用于判断节点连通性和延迟</small></label>
      <button type="button" data-remove-group="${index}">删除</button></div>`).join("");
    groupOptions.querySelectorAll("[data-remove-group]").forEach((button) => button.onclick = () => { const index = Number(button.dataset.removeGroup); const removed = data.groups[index]; data.groups.splice(index, 1); delete data.targets[removed.target]; data.routes.forEach((route) => { if (route.target === removed.target) route.target = "DIRECT"; }); data.standalone_urls?.forEach((item) => { if (item.target === removed.target) item.target = "DIRECT"; }); data.standalone_rules?.forEach((item) => { if (item.target === removed.target) item.target = "DIRECT"; }); data.groups.forEach((group) => { if (group.fallback === removed.target) group.fallback = "DIRECT"; }); if (data.final === removed.target) data.final = "DIRECT"; renderGroups(); renderRoutes(); renderStandalone(); renderRuleLists(); });
  };
  renderGroups();
  document.querySelector("#add-group").onclick = () => { let n = data.groups.length + 1; let target = `GROUP_${n}`; while (data.targets[target]) target = `GROUP_${++n}`; data.targets[target] = target; data.groups.push({ target, pattern: "(节点|Node)", flags: "i", url: speedTests.Gstatic, interval: 30, tolerance: 10, fallback: "DIRECT" }); renderGroups(); renderRoutes(); renderStandalone(); renderRuleLists(); };
  document.querySelector("#generate-button").onclick = () => {
    source = JSON.parse(JSON.stringify(data));
    groupOptions.querySelectorAll(".group-row").forEach((row) => {
      const group = source.groups[Number(row.dataset.group)];
      row.querySelectorAll("[data-field]").forEach((input) => { group[input.dataset.field] = input.value; });
      const display = row.querySelector("[data-display]"); if (display) source.targets[group.target] = display.value.trim() || group.target;
      group.interval = Number(document.querySelector("#group-interval").value);
      group.tolerance = Number(document.querySelector("#group-tolerance").value);
      group.flags ||= "i"; group.fallback ||= "DIRECT";
    });
    source.routes.forEach((route, index) => { const target = document.querySelector(`[data-target-route="${index}"]`); if (target) route.target = target.value; });
    source.standalone_urls = data.standalone_urls || [];
    source.standalone_rules = data.standalone_rules || [];
    source.routes = source.routes.filter((route) => route.enabled !== false);
    document.querySelectorAll("[data-rule-values]").forEach((area) => { const index = Number(area.dataset.ruleValues); const type = document.querySelector(`[data-rule-type="${index}"]`).value; source.standalone_rules[index][type] = area.value.split(/\r?\n/).map((value) => value.trim()).filter(Boolean); });
    sourceEl.value = JSON.stringify(source, null, 2);
    render(); document.querySelector("#converter").classList.remove("hidden");
    document.querySelector("#converter").scrollIntoView({ behavior: "smooth", block: "start" });
  };
}

function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[character])); }

function setMode(mode) {
  const generator = mode === "generator";
  document.querySelector("#generator").classList.toggle("hidden", !generator);
  document.querySelector("#converter-toolbar").classList.toggle("hidden", generator);
  document.querySelector("#converter").classList.toggle("hidden", generator);
  document.querySelectorAll(".mode").forEach((button) => { const active = button.dataset.mode === mode; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); });
}

sourceEl.addEventListener("input", render);
document.querySelector("#format-button").onclick = () => { try { sourceEl.value = JSON.stringify(JSON.parse(sourceEl.value), null, 2); render(); } catch { render(); } };
document.querySelector("#reset-button").onclick = async () => { await loadDefault(); if (source) setupGenerator(source); };
document.querySelector("#file-input").onchange = async (event) => { const file = event.target.files[0]; if (file) { sourceEl.value = await file.text(); render(); try { source = JSON.parse(sourceEl.value); validate(source); setupGenerator(source); } catch {} } };
document.querySelectorAll(".tab").forEach((tab) => tab.onclick = () => { document.querySelectorAll(".tab").forEach((item) => { const active = item === tab; item.classList.toggle("active", active); item.setAttribute("aria-selected", String(active)); }); outputType = tab.dataset.output; render(); });
document.querySelector("#copy-button").onclick = async () => { if (outputEl.value) { await navigator.clipboard.writeText(outputEl.value); statusEl.textContent = "已复制"; } };
document.querySelector("#download-button").onclick = () => { if (!outputEl.value) return; const ext = outputType === "clash" ? "js" : "conf"; const blob = new Blob([outputEl.value], { type: "text/plain;charset=utf-8" }); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `generated.${ext}` }); link.click(); URL.revokeObjectURL(link.href); };
document.querySelector("#export-source-button").onclick = () => { const blob = new Blob([sourceEl.value], { type: "application/json;charset=utf-8" }); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: "rules-source.json" }); link.click(); URL.revokeObjectURL(link.href); };
document.querySelectorAll(".mode").forEach((button) => button.onclick = () => setMode(button.dataset.mode));
loadDefault().then(() => { if (source) setupGenerator(source); });
