const sourceEl = document.querySelector("#source");
const outputEl = document.querySelector("#output");
const statusEl = document.querySelector("#status");
const summaryEl = document.querySelector("#summary");
let source = null;
let outputType = "clash";
const routeDescriptions = { Apple: "Apple 服务直连", "指定 IP / US": "指定地址走美国节点", AI: "Claude、ChatGPT、Gemini 等", "Daily / SEA": "Atlassian、OKX", GitHub: "GitHub 服务", LINE: "LINE 服务", Steam: "Steam 游戏服务", Netflix: "Netflix 与 Fast.com", Stream: "YouTube、TikTok", Google: "Google 服务", "中国大陆直连": "中国大陆 IP 直接连接", "局域网直连": "局域网、保留地址与特殊网段", "1Password": "1Password 服务", "Immersive Translate": "沉浸式翻译服务", "路由云": "路由云服务", ITSSX: "ITSSX 服务", CSUST: "校园网域名", OpenRouter: "OpenRouter 服务" };
const speedTests = { Cloudflare: "http://cp.cloudflare.com/generate_204", Fast: "https://fast.com", Gstatic: "http://www.gstatic.com/generate_204" };

const marker = (type) => type === "clash"
  ? "// Generated by the Clash JS / Shadowrocket rule generator; edit rules-source.json instead."
  : "# Generated by the Clash JS / Shadowrocket rule generator; edit rules-source.json instead.";

function expandedRoutes(data) {
  return [...data.routes.flatMap((route) => (route._domainTargets?.length ? route.domains.map((domain, index) => ({ name: route.name, target: route._domainTargets[index] || route.target, domains: [domain] })) : [{
    ...route,
    domains: [...(route.domain_sets || []).flatMap((name) => data.rule_sets[name]), ...(route.domains || [])],
  }])), ...(data.standalone_urls || []).map((item) => ({ name: item.name, target: item.target, domains: [item.domain] })), ...(data.standalone_rules || [])];
}

function rules(data, finalType) {
  return [...expandedRoutes(data).flatMap((route) => {
    const target = data.targets[route.target];
    return [
      ...(route.geoips || []).map((value) => [`GEOIP,${value},${target}`, route.name]),
      ...(route.domains || []).map((value) => [`DOMAIN-SUFFIX,${value},${target}`, route.name]),
      ...(route.keywords || []).map((value) => [`DOMAIN-KEYWORD,${value},${target}`, route.name]),
      ...(route.cidrs || []).map((value) => [`IP-CIDR,${value},${target},no-resolve`, route.name]),
    ];
  }), [`${finalType},${data.targets[data.final]}`, null]];
}

function renderClash(data) {
  const groups = data.groups.map((group) => ({
    target: group.target, pattern: group.pattern, flags: group.flags || "",
    url: group.url, interval: group.interval, tolerance: group.tolerance, fallback: group.fallback,
  }));
  return `${marker("clash")}\n\nconst TARGETS = Object.freeze(${JSON.stringify(data.targets, null, 2)});\nconst GROUP_CONFIGS = ${JSON.stringify(groups, null, 2)};\nconst ROUTES = ${JSON.stringify(expandedRoutes(data), null, 2)};\nconst FINAL_TARGET = ${JSON.stringify(data.final)};\n\nfunction compileRoute(route) {\n  const target = TARGETS[route.target];\n  return [\n    ...(route.geoips || []).map((value) => \`GEOIP,\${value},\${target}\`),\n    ...(route.domains || []).map((value) => \`DOMAIN-SUFFIX,\${value},\${target}\`),\n    ...(route.keywords || []).map((value) => \`DOMAIN-KEYWORD,\${value},\${target}\`),\n    ...(route.cidrs || []).map((value) => \`IP-CIDR,\${value},\${target},no-resolve\`),\n  ];\n}\n\nfunction buildProxyGroups(proxies) {\n  return GROUP_CONFIGS.map((group) => {\n    const match = new RegExp(group.pattern, group.flags);\n    const matchedProxies = proxies.filter((proxy) => match.test(proxy.name)).map((proxy) => proxy.name);\n    return { name: TARGETS[group.target], type: "url-test", url: group.url, interval: group.interval, tolerance: group.tolerance, proxies: matchedProxies.length ? matchedProxies : [TARGETS[group.fallback]] };\n  });\n}\n\nfunction main(config) {\n  config["proxy-groups"] ||= [];\n  config["proxy-groups"].unshift(...buildProxyGroups(config.proxies || []));\n  config.rules = [...ROUTES.flatMap(compileRoute), \`MATCH,\${TARGETS[FINAL_TARGET]}\`, ...(config.rules || [])];\n  return config;\n}\n`;
}

function renderShadowrocket(data) {
  const dns = data.shadowrocket_dns;
  const lines = [marker("shadowrocket"), "# Clash 在零匹配时回退到 fallback；Shadowrocket 使用静态策略组。", "", "[General]",
    `ipv6 = ${dns.ipv6}`, `private-ip-answer = ${dns.private_ip_answer}`, `dns-server = ${dns.servers.join(",")}`,
    `fallback-dns-server = ${dns.fallback_servers.join(",")}`, `proxy-dns-server = ${dns.proxy_servers.join(",")}`,
    `always-real-ip = ${dns.always_real_ip.join(",")}`, "", "[Proxy Group]"];
  for (const group of data.groups) lines.push(`${data.targets[group.target]} = url-test,url=${group.url},interval=${group.interval},tolerance=${group.tolerance},policy-regex-filter=${group.flags === "i" ? "(?i)" : ""}${group.pattern}`);
  lines.push("", "[Rule]");
  let previous = null;
  for (const [rule, name] of rules(data, "FINAL")) { if (name && name !== previous) { lines.push("", `# ${name}`); previous = name; } lines.push(rule); }
  lines.push("", "[Host]");
  for (const mapping of dns.host_servers) for (const pattern of mapping.patterns) lines.push(`${pattern} = server:${mapping.server}`);
  return `${lines.join("\n")}\n`;
}

function validate(data) {
  if (!data || data.version !== 1 || !data.targets || !Array.isArray(data.groups) || !Array.isArray(data.routes) || !data.final) throw new Error("必须包含 version、targets、groups、routes 和 final 字段");
  for (const route of data.routes) if (!data.targets[route.target]) throw new Error(`规则「${route.name || "未命名"}」引用了未知策略`);
  if (!data.targets[data.final]) throw new Error("final 引用了未知策略");
  if (!data.shadowrocket_dns) throw new Error("缺少 shadowrocket_dns 配置");
}

function render() {
  try {
    source = JSON.parse(sourceEl.value); validate(source);
    outputEl.value = outputType === "clash" ? renderClash(source) : renderShadowrocket(source);
    const count = rules(source, "MATCH").length - 1;
    summaryEl.textContent = `${count} 条规则 · ${source.routes.length} 个分类 · 浏览器本地生成`;
    statusEl.textContent = "校验通过"; statusEl.className = "";
  } catch (error) { statusEl.textContent = error.message; statusEl.className = "error"; summaryEl.textContent = "规则源无效"; outputEl.value = ""; }
}

async function loadDefault() {
  try { sourceEl.value = JSON.stringify(await (await fetch("rules-source.json")).json(), null, 2); render(); }
  catch { statusEl.textContent = "请导入 rules-source.json"; statusEl.className = "error"; }
}

function setupGenerator(data) {
  if (!data.standalone_urls) {
    data.standalone_urls = [];
    for (const route of data.routes.filter((item) => ["Direct", "Daily / SEA"].includes(item.name))) {
      data.standalone_urls.push(...(route.domains || []).map((domain) => ({ name: domain, domain, target: route.target })));
      route.domains = [];
    }
  }
  let editingRoute = null;
  const renderRoutes = () => { document.querySelector("#route-options").innerHTML = data.routes.map((route, index) => `<div class="route-option"><div><input type="checkbox" data-route="${index}" ${route.enabled !== false ? "checked" : ""}><strong>${route.name}</strong></div><em>${routeDescriptions[route.name] || "自定义分流规则"}</em><select data-target-route="${index}" aria-label="${route.name} 导向节点组">${Object.entries(data.targets).map(([key, name]) => `<option value="${key}" ${route.target === key ? "selected" : ""}>${name}</option>`).join("")}</select><button type="button" class="edit-domains" data-edit-route="${index}">编辑网址列表</button></div>`).join("");
    document.querySelectorAll("[data-route]").forEach((input) => input.onchange = () => { data.routes[input.dataset.route].enabled = input.checked; });
    document.querySelectorAll("[data-target-route]").forEach((select) => select.onchange = () => { data.routes[select.dataset.targetRoute].target = select.value; });
    document.querySelectorAll("[data-edit-route]").forEach((button) => button.onclick = () => { editingRoute = Number(button.dataset.editRoute); const route = data.routes[editingRoute]; document.querySelector("#drawer-title").textContent = `${route.name} · 网址列表`; document.querySelector("#drawer-items").innerHTML = (route.domains || []).map((domain, index) => `<div class="drawer-item"><input data-drawer-domain="${index}" value="${escapeHtml(domain)}"><select data-drawer-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${key}" ${route.target === key ? "selected" : ""}>${name}</option>`).join("")}</select></div>`).join(""); document.querySelector("#drawer-backdrop").classList.remove("hidden"); document.querySelector("#domain-drawer").classList.add("open"); });
  };
  renderRoutes();
  const renderStandalone = () => { document.querySelector("#standalone-options").innerHTML = (data.standalone_urls || []).map((item, index) => `<div class="standalone-row"><input data-standalone-domain="${index}" value="${escapeHtml(item.domain)}"><select data-standalone-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${key}" ${item.target === key ? "selected" : ""}>${name}</option>`).join("")} </select></div>`).join(""); document.querySelectorAll("[data-standalone-domain]").forEach((input) => input.onchange = () => { data.standalone_urls[input.dataset.standaloneDomain].domain = input.value.trim(); }); document.querySelectorAll("[data-standalone-target]").forEach((select) => select.onchange = () => { data.standalone_urls[select.dataset.standaloneTarget].target = select.value; }); };
  renderStandalone();
  document.querySelector("#add-standalone").onclick = () => { data.standalone_urls ||= []; data.standalone_urls.push({ name: "新网址", domain: "example.com", target: "DIRECT" }); renderStandalone(); };
  const renderRules = () => { document.querySelector("#rule-options").innerHTML = (data.standalone_rules || []).map((item, index) => `<div class="standalone-rule"><strong>${escapeHtml(item.name)}</strong><code>${escapeHtml([...(item.geoips || []), ...(item.cidrs || []), ...(item.domains || [])].join(", "))}</code><select data-rule-target="${index}">${Object.entries(data.targets).map(([key, name]) => `<option value="${key}" ${item.target === key ? "selected" : ""}>${name}</option>`).join("")}</select></div>`).join(""); document.querySelectorAll("[data-rule-target]").forEach((select) => select.onchange = () => { data.standalone_rules[select.dataset.ruleTarget].target = select.value; }); };
  data.standalone_rules ||= []; renderRules();
  document.querySelector("#add-rule").onclick = () => { data.standalone_rules.push({ name: "新规则", target: "DIRECT", cidrs: ["192.0.2.0/24"] }); renderRules(); };
  document.querySelector("#add-route").onclick = () => { data.routes.push({ name: `新策略 ${data.routes.length + 1}`, target: "DIRECT", domains: [], keywords: [] }); renderRoutes(); };
  document.querySelector("#save-domains").onclick = () => { if (editingRoute === null) return; data.routes[editingRoute].domain_sets = []; data.routes[editingRoute].domains = [...document.querySelectorAll("[data-drawer-domain]")].map((input) => input.value.trim()).filter(Boolean); data.routes[editingRoute]._domainTargets = [...document.querySelectorAll("[data-drawer-target]")].map((select) => select.value); document.querySelector("#drawer-backdrop").click(); };
  document.querySelector("#close-drawer").onclick = () => document.querySelector("#drawer-backdrop").click();
  document.querySelector("#drawer-backdrop").onclick = () => { document.querySelector("#drawer-backdrop").classList.add("hidden"); document.querySelector("#domain-drawer").classList.remove("open"); };
  document.querySelector("#group-interval").value = data.groups[0]?.interval ?? 30;
  document.querySelector("#group-tolerance").value = data.groups[0]?.tolerance ?? 10;
  const groupOptions = document.querySelector("#group-options");
  const renderGroups = () => {
    groupOptions.innerHTML = data.groups.map((group, index) => `<div class="group-row" data-group="${index}">
      <label><span>策略键</span><input data-field="target" value="${escapeHtml(group.target)}" placeholder="例如 SEA"><small>规则引用的内部名称</small></label>
      <label><span>节点名称正则</span><input data-field="pattern" value="${escapeHtml(group.pattern)}" placeholder="例如 新加坡|SG"><small>匹配节点名称后加入此组</small></label>
      <label><span>测速服务</span><select data-field="url">${Object.entries(speedTests).map(([name, url]) => `<option value="${url}" ${group.url === url ? "selected" : ""}>${name}</option>`).join("")}</select><small>用于判断节点连通性和延迟</small></label>
      <button type="button" data-remove-group="${index}">删除</button></div>`).join("");
    groupOptions.querySelectorAll("[data-remove-group]").forEach((button) => button.onclick = () => { data.groups.splice(Number(button.dataset.removeGroup), 1); renderGroups(); renderRoutes(); });
  };
  renderGroups();
  document.querySelector("#add-group").onclick = () => { const target = `GROUP_${data.groups.length + 1}`; data.targets[target] = target; data.groups.push({ target, pattern: "(节点|Node)", flags: "i", url: speedTests.Gstatic, interval: 30, tolerance: 10, fallback: "DIRECT" }); renderGroups(); renderRoutes(); };
  document.querySelector("#generate-button").onclick = () => {
    source = JSON.parse(JSON.stringify(data));
    groupOptions.querySelectorAll(".group-row").forEach((row) => {
      const group = source.groups[Number(row.dataset.group)];
      row.querySelectorAll("[data-field]").forEach((input) => { group[input.dataset.field] = input.value; });
      group.interval = Number(document.querySelector("#group-interval").value);
      group.tolerance = Number(document.querySelector("#group-tolerance").value);
      group.flags ||= "i"; group.fallback ||= "DIRECT";
    });
    source.routes.forEach((route, index) => { const target = document.querySelector(`[data-target-route="${index}"]`); if (target) route.target = target.value; });
    source.standalone_urls = data.standalone_urls || [];
    source.standalone_rules = data.standalone_rules || [];
    source.routes = source.routes.filter((route) => route.enabled !== false);
    sourceEl.value = JSON.stringify(source, null, 2);
    render(); document.querySelector("#converter").classList.remove("hidden");
    document.querySelector("#converter").scrollIntoView({ behavior: "smooth", block: "start" });
  };
}

function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[character])); }

function setMode(mode) {
  const generator = mode === "generator";
  document.querySelector("#generator").classList.toggle("hidden", !generator);
  document.querySelector("#converter-toolbar").classList.toggle("hidden", generator);
  document.querySelector("#converter").classList.toggle("hidden", generator);
  document.querySelectorAll(".mode").forEach((button) => button.classList.toggle("active", button.dataset.mode === mode));
}

sourceEl.addEventListener("input", render);
document.querySelector("#format-button").onclick = () => { try { sourceEl.value = JSON.stringify(JSON.parse(sourceEl.value), null, 2); render(); } catch { render(); } };
document.querySelector("#reset-button").onclick = loadDefault;
document.querySelector("#file-input").onchange = async (event) => { const file = event.target.files[0]; if (file) { sourceEl.value = await file.text(); render(); } };
document.querySelectorAll(".tab").forEach((tab) => tab.onclick = () => { document.querySelectorAll(".tab").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); outputType = tab.dataset.output; render(); });
document.querySelector("#copy-button").onclick = async () => { if (outputEl.value) { await navigator.clipboard.writeText(outputEl.value); statusEl.textContent = "已复制"; } };
document.querySelector("#download-button").onclick = () => { if (!outputEl.value) return; const ext = outputType === "clash" ? "js" : "conf"; const blob = new Blob([outputEl.value], { type: "text/plain;charset=utf-8" }); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `generated.${ext}` }); link.click(); URL.revokeObjectURL(link.href); };
document.querySelectorAll(".mode").forEach((button) => button.onclick = () => setMode(button.dataset.mode));
loadDefault().then(() => { if (source) setupGenerator(source); });
