#!/usr/bin/env python3
"""Generate Clash override JS and Shadowrocket config from rules-source.json."""

from __future__ import annotations

import ipaddress
import json
import re
import sys
from pathlib import Path
from typing import Any


SOURCE_NAME = "rules-source.json"
CLASH_NAME = "clash.js"
SHADOWROCKET_NAME = "shadowrocket.conf"
CLASH_MARKER = "// Generated by rules_generator.py; edit rules-source.json instead."
SHADOWROCKET_MARKER = (
    "# Generated by rules_generator.py; edit rules-source.json instead."
)


def load_source(path: Path) -> dict[str, Any]:
    try:
        source = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ValueError(f"找不到 {path.name}，请把它和生成器放在同一目录") from error
    except json.JSONDecodeError as error:
        raise ValueError(
            f"{path.name}:{error.lineno}:{error.colno} JSON 格式错误：{error.msg}"
        ) from error

    if not isinstance(source, dict):
        raise ValueError("规则源的顶层必须是 JSON 对象")
    return source


def require_strings(values: Any, location: str) -> list[str]:
    if values is None:
        return []
    if not isinstance(values, list) or not all(
        isinstance(value, str) and value for value in values
    ):
        raise ValueError(f"{location} 必须是非空字符串数组")
    for value in values:
        if any(character in value for character in ",\r\n"):
            raise ValueError(f"{location} 的值不能包含逗号或换行：{value!r}")
    return values


def validate_source(source: dict[str, Any]) -> None:
    if source.get("version") != 1:
        raise ValueError("只支持 version: 1")

    targets = source.get("targets")
    if not isinstance(targets, dict) or not targets:
        raise ValueError("targets 必须是非空对象")
    for key, name in targets.items():
        if not isinstance(key, str) or not isinstance(name, str) or not name:
            raise ValueError("targets 的键和值必须是非空字符串")
        if any(character in name for character in ",\r\n="):
            raise ValueError(f"策略名称不能包含逗号、等号或换行：{name!r}")

    groups = source.get("groups")
    if not isinstance(groups, list):
        raise ValueError("groups 必须是数组")
    group_targets: set[str] = set()
    for index, group in enumerate(groups):
        location = f"groups[{index}]"
        if not isinstance(group, dict):
            raise ValueError(f"{location} 必须是对象")
        target = group.get("target")
        fallback = group.get("fallback")
        if target not in targets:
            raise ValueError(f"{location}.target 引用了未知策略：{target!r}")
        if fallback not in targets:
            raise ValueError(f"{location}.fallback 引用了未知策略：{fallback!r}")
        if target in group_targets:
            raise ValueError(f"策略组重复：{target}")
        group_targets.add(target)

        pattern = group.get("pattern")
        flags = group.get("flags", "")
        if not isinstance(pattern, str) or not pattern:
            raise ValueError(f"{location}.pattern 必须是非空字符串")
        if flags not in {"", "i"}:
            raise ValueError(f"{location}.flags 目前只支持空字符串或 i")
        try:
            re.compile(pattern, re.IGNORECASE if flags == "i" else 0)
        except re.error as error:
            raise ValueError(f"{location}.pattern 正则错误：{error}") from error

        url = group.get("url")
        if not isinstance(url, str) or not url.startswith(("http://", "https://")):
            raise ValueError(f"{location}.url 必须是 HTTP(S) URL")
        for key in ("interval", "tolerance"):
            if not isinstance(group.get(key), int) or group[key] < 0:
                raise ValueError(f"{location}.{key} 必须是非负整数")

    rule_sets = source.get("rule_sets")
    if not isinstance(rule_sets, dict):
        raise ValueError("rule_sets 必须是对象")
    for name, values in rule_sets.items():
        require_strings(values, f"rule_sets.{name}")

    routes = source.get("routes")
    if not isinstance(routes, list) or not routes:
        raise ValueError("routes 必须是非空数组")
    for index, route in enumerate(routes):
        location = f"routes[{index}]"
        if not isinstance(route, dict):
            raise ValueError(f"{location} 必须是对象")
        if not isinstance(route.get("name"), str) or not route["name"]:
            raise ValueError(f"{location}.name 必须是非空字符串")
        target = route.get("target")
        if target not in targets:
            raise ValueError(f"{location}.target 引用了未知策略：{target!r}")
        if target not in group_targets and targets[target] not in {"DIRECT", "REJECT"}:
            raise ValueError(f"{location}.target 没有对应策略组：{target}")

        domain_sets = require_strings(route.get("domain_sets"), f"{location}.domain_sets")
        for set_name in domain_sets:
            if set_name not in rule_sets:
                raise ValueError(f"{location} 引用了未知规则集：{set_name}")
        require_strings(route.get("domains"), f"{location}.domains")
        require_strings(route.get("keywords"), f"{location}.keywords")
        require_strings(route.get("geoips"), f"{location}.geoips")
        for cidr in require_strings(route.get("cidrs"), f"{location}.cidrs"):
            try:
                ipaddress.ip_network(cidr, strict=False)
            except ValueError as error:
                raise ValueError(f"{location} 包含无效 CIDR：{cidr}") from error

    final = source.get("final")
    if final not in targets:
        raise ValueError(f"final 引用了未知策略：{final!r}")
    if final not in group_targets and targets[final] not in {"DIRECT", "REJECT"}:
        raise ValueError(f"final 没有对应策略组：{final}")


def expanded_routes(source: dict[str, Any]) -> list[dict[str, Any]]:
    result = []
    for route in source["routes"]:
        domains: list[str] = []
        for set_name in route.get("domain_sets", []):
            domains.extend(source["rule_sets"][set_name])
        domains.extend(route.get("domains", []))

        expanded = {
            "name": route["name"],
            "target": route["target"],
        }
        for key, values in (
            ("geoips", route.get("geoips", [])),
            ("domains", domains),
            ("keywords", route.get("keywords", [])),
            ("cidrs", route.get("cidrs", [])),
        ):
            if values:
                expanded[key] = values
        result.append(expanded)
    return result


def compile_rules(
    source: dict[str, Any],
    final_type: str,
) -> list[tuple[str | None, str]]:
    targets = source["targets"]
    result: list[tuple[str | None, str]] = []
    for route in expanded_routes(source):
        target = targets[route["target"]]
        rules = [
            *(f"GEOIP,{value},{target}" for value in route.get("geoips", [])),
            *(
                f"DOMAIN-SUFFIX,{value},{target}"
                for value in route.get("domains", [])
            ),
            *(
                f"DOMAIN-KEYWORD,{value},{target}"
                for value in route.get("keywords", [])
            ),
            *(
                f"IP-CIDR,{value},{target},no-resolve"
                for value in route.get("cidrs", [])
            ),
        ]
        result.extend((route["name"], rule) for rule in rules)
    result.append((None, f"{final_type},{targets[source['final']]}"))
    return result


def render_clash(source: dict[str, Any]) -> str:
    targets = json.dumps(source["targets"], ensure_ascii=False, indent=2)
    groups = json.dumps(source["groups"], ensure_ascii=False, indent=2)
    routes = json.dumps(expanded_routes(source), ensure_ascii=False, indent=2)
    final = json.dumps(source["final"], ensure_ascii=False)

    return f"""{CLASH_MARKER}

const TARGETS = Object.freeze({targets});
const GROUP_CONFIGS = {groups};
const ROUTES = {routes};
const FINAL_TARGET = {final};

function compileRoute(route) {{
  const target = TARGETS[route.target];
  return [
    ...(route.geoips || []).map((value) => `GEOIP,${{value}},${{target}}`),
    ...(route.domains || []).map(
      (value) => `DOMAIN-SUFFIX,${{value}},${{target}}`
    ),
    ...(route.keywords || []).map(
      (value) => `DOMAIN-KEYWORD,${{value}},${{target}}`
    ),
    ...(route.cidrs || []).map(
      (value) => `IP-CIDR,${{value}},${{target}},no-resolve`
    ),
  ];
}}

function buildProxyGroups(proxies) {{
  return GROUP_CONFIGS.map((group) => {{
    const match = new RegExp(group.pattern, group.flags);
    const matchedProxies = proxies
      .filter((proxy) => match.test(proxy.name))
      .map((proxy) => proxy.name);

    return {{
      name: TARGETS[group.target],
      type: "url-test",
      url: group.url,
      interval: group.interval,
      tolerance: group.tolerance,
      proxies: matchedProxies.length > 0
        ? matchedProxies
        : [TARGETS[group.fallback]],
    }};
  }});
}}

function buildRules() {{
  return [
    ...ROUTES.flatMap(compileRoute),
    `MATCH,${{TARGETS[FINAL_TARGET]}}`,
  ];
}}

function main(config) {{
  const newGroups = buildProxyGroups(config.proxies || []);

  if (!config["proxy-groups"]) {{
    config["proxy-groups"] = [];
  }}

  config["proxy-groups"].unshift(...newGroups);
  config.rules = [
    ...buildRules(),
    ...(config.rules || []),
  ];

  return config;
}}
"""


def shadowrocket_pattern(group: dict[str, Any]) -> str:
    prefix = "(?i)" if group.get("flags") == "i" else ""
    return prefix + group["pattern"]


def render_shadowrocket(source: dict[str, Any]) -> str:
    lines = [
        SHADOWROCKET_MARKER,
        "# Clash 在零匹配时回退 DIRECT；Shadowrocket 静态策略组无等价条件分支。",
        "",
        "[Proxy Group]",
    ]
    targets = source["targets"]
    for group in source["groups"]:
        lines.append(
            f"{targets[group['target']]} = url-test,"
            f"url={group['url']},"
            f"interval={group['interval']},"
            f"tolerance={group['tolerance']},"
            f"policy-regex-filter={shadowrocket_pattern(group)}"
        )

    lines.extend(["", "[Rule]"])
    previous_route = object()
    for route_name, rule in compile_rules(source, "FINAL"):
        if route_name != previous_route and route_name is not None:
            if previous_route is not None:
                lines.append("")
            lines.append(f"# {route_name}")
        lines.append(rule)
        previous_route = route_name
    return "\n".join(lines) + "\n"


def write_generated(path: Path, content: str, marker: str) -> None:
    if path.exists():
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
        if first_line != [marker]:
            raise ValueError(f"拒绝覆盖非生成文件：{path.name}")
    path.write_text(content, encoding="utf-8")


def self_test(source: dict[str, Any]) -> None:
    clash = render_clash(source)
    shadowrocket = render_shadowrocket(source)
    clash_rules = [
        rule.replace("FINAL,", "MATCH,", 1)
        for _, rule in compile_rules(source, "FINAL")
    ]
    expected = [rule for _, rule in compile_rules(source, "MATCH")]

    assert clash.startswith(CLASH_MARKER)
    assert shadowrocket.startswith(SHADOWROCKET_MARKER)
    assert clash_rules == expected
    assert "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve" in shadowrocket
    assert f"FINAL,{source['targets'][source['final']]}" in shadowrocket
    assert len(expected) == 80


def main() -> int:
    directory = Path(__file__).resolve().parent
    try:
        source = load_source(directory / SOURCE_NAME)
        validate_source(source)
        self_test(source)

        if sys.argv[1:] == ["--check"]:
            print("检查通过：规则源有效，80 条规则双端语义一致")
            return 0
        if sys.argv[1:]:
            raise ValueError("无需输入参数；可选参数只有 --check")

        clash_path = directory / CLASH_NAME
        shadowrocket_path = directory / SHADOWROCKET_NAME
        write_generated(clash_path, render_clash(source), CLASH_MARKER)
        write_generated(
            shadowrocket_path,
            render_shadowrocket(source),
            SHADOWROCKET_MARKER,
        )
        print(f"生成完成：{clash_path.name}、{shadowrocket_path.name}")
    except (OSError, ValueError, AssertionError) as error:
        print(f"生成失败：{error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
